#config/preprocessing_config.yaml
datasets:
  persona-chat:
    name: "Cynaptics/persona-chat"
    subsets: ["train"]
    text_key: "dialogue"
    id_key: "conv_id"
    is_list: true
    role_prefixes:
      "Persona A:": "user"
      "Persona B:": "bot"

  daily-dialog:
    name: "pixelsandpointers/better_daily_dialog"
    subsets: ["train", "validation", "test"]
    text_key: "utterance"
    id_key: "dialog_id"
    is_list: false
    role_assignment: "alternating"

  instruction-sets:
    sources:
      - path: "Data/instructions_outputs.json"
        type: "basic"
      - path: "Data/python_functions_renamed.json"
        type: "basic"
      - path : "Data/stackoverflow_qa.json"
        type: "basic"
      - path: "Data/kodcode_formatted.json"
        type: "with_difficulty"
        difficulty_file: "Data/gpt_difficulty.json"

splitting:
  test_size: 0.15
  val_ratio_of_test: 0.48
  random_state: 42
  instruction_test_size: 0.1 # optional override

scanning:
  verbose: False #Set to True only if you want per-match logs

output:
  base_dir: "output/"
  file_prefixes:
    persona: "persona"
    daily: "daily_dialog"
    merged: "merged"
    formatted: "formatted_merged"
    instruction: "instruction"
    formatted_instr: "formatted_instruction"

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_file: preprocessing.log
